In [1]:
import pandas as pd
import pickle
unique_calls = pd.read_pickle("cdr_clean_unique_calls_update_num2.pkl")

In [2]:
columns = unique_calls[['unique_call_id', 'dateTimeConnect', 'dateTimeDisconnect']]
columns.head()

   unique_call_id     dateTimeConnect  dateTimeDisconnect
0          752520 2024-01-01 01:20:14 2024-01-01 01:20:22
1          752521 2024-01-01 03:08:02 2024-01-01 03:08:14
2          752522                 NaT 2024-01-01 05:07:47
3          752523 2024-01-01 05:41:31 2024-01-01 05:42:05
4          752524 2024-01-01 06:07:15 2024-01-01 06:07:50

In [3]:
# pro kazde unique_call_id najit min dateTimeConnect a maxTimeDisconnect
unique_calls = columns.groupby(['unique_call_id']).agg({"dateTimeConnect":"min","dateTimeDisconnect":"max"})

In [4]:
unique_calls['duration_for_unique'] = unique_calls['dateTimeDisconnect'] - unique_calls['dateTimeConnect']

unique_calls.head()

                   dateTimeConnect  dateTimeDisconnect duration_for_unique
unique_call_id
0              2024-01-16 10:11:52 2024-01-16 10:16:23     0 days 00:04:31
1              2024-01-16 10:11:49 2024-01-16 10:12:25     0 days 00:00:36
2              2024-01-16 10:11:50 2024-01-16 10:12:29     0 days 00:00:39
4              2024-01-16 10:11:51 2024-01-16 10:17:31     0 days 00:05:40
8              2024-01-16 10:11:53 2024-01-16 10:12:32     0 days 00:00:39

In [5]:
# nepocita s NaT, proto count je mensi nez celkovy pocet jedinecnych hovoru
unique_calls.describe()

,dateTimeConnect,dateTimeDisconnect,duration_for_unique
count,1751501,2234015,1751501
mean,2024-02-13 22:21:46.143080448,2024-02-14 00:15:24.818769664,0 days 00:02:21.180192874
min,2024-01-01 00:12:37,2024-01-01 00:13:07,0 days 00:00:00
25%,2024-01-23 07:23:43,2024-01-23 07:44:32,0 days 00:00:16
50%,2024-02-13 11:25:02,2024-02-13 12:59:07,0 days 00:00:56
75%,2024-03-06 14:30:36,2024-03-06 16:13:50.500000,0 days 00:02:33
max,2024-03-31 23:49:49,2024-03-31 23:55:03,0 days 12:00:00
std,NaN,NaN,0 days 00:05:29.364158669

In [6]:
unique_calls.to_pickle('duration_unique_calls.pkl')

In [7]:
unique_calls.shape

(2234015, 3)

In [ ]:
# kolik hovoru je nespojenych
unique_calls.isna().sum()

dateTimeConnect        482514
dateTimeDisconnect          0
duration_for_unique    482514
dtype: int64

In [10]:
# rozdil mezi celkovym poctem unikatnich hovoru a poctem spojenych hovoru = pocet nespojenych hovoru
2234015 - 1751501

482514

In [11]:
unique_calls['month'] = unique_calls['dateTimeDisconnect'].dt.to_period('M')

unique_month_calls = (
    unique_calls.groupby('month').size()
)

print(unique_month_calls)

month
2024-01    807662
2024-02    727094
2024-03    699259
Freq: M, dtype: int64

In [12]:
unique_calls['week'] = unique_calls['dateTimeDisconnect'].dt.to_period('W')

unique_week_calls = (
    unique_calls.groupby('week').size()
)

print(unique_week_calls)
unique_week_calls.sum()

week
2024-01-01/2024-01-07    136128
2024-01-08/2024-01-14    196084
2024-01-15/2024-01-21    185385
2024-01-22/2024-01-28    177745
2024-01-29/2024-02-04    184060
2024-02-05/2024-02-11    175856
2024-02-12/2024-02-18    166575
2024-02-19/2024-02-25    170868
2024-02-26/2024-03-03    174518
2024-03-04/2024-03-10    172665
2024-03-11/2024-03-17    169397
2024-03-18/2024-03-24    169851
2024-03-25/2024-03-31    154883
Freq: W-SUN, dtype: int64

np.int64(2234015)

In [13]:
unique_calls['week'] = unique_calls['dateTimeDisconnect'].dt.to_period('W')

unique_week_calls = (
    unique_calls.groupby('week').agg({'duration_for_unique':'median'}) #,'duration_for_unique':'count', 'duration_for_unique': 'max', 'duration_for_unique':'min'})
)

print(unique_week_calls)
unique_week_calls.sum() 
print()

                      duration_for_unique
week
2024-01-01/2024-01-07     0 days 00:00:37
2024-01-08/2024-01-14     0 days 00:00:35
2024-01-15/2024-01-21     0 days 00:00:35
2024-01-22/2024-01-28     0 days 00:00:31
2024-01-29/2024-02-04     0 days 00:00:31
2024-02-05/2024-02-11     0 days 00:00:32
2024-02-12/2024-02-18     0 days 00:00:30
2024-02-19/2024-02-25     0 days 00:00:30
2024-02-26/2024-03-03     0 days 00:00:31
2024-03-04/2024-03-10     0 days 00:00:30
2024-03-11/2024-03-17     0 days 00:00:29
2024-03-18/2024-03-24     0 days 00:00:28
2024-03-25/2024-03-31     0 days 00:00:30