In [8]:
import pandas as pd
import pickle
data = pd.read_pickle("cdr_clean_no_duplicates.pkl")

In [9]:
data['dateOrigin'] = data['dateTimeOrigination'].dt.date

In [10]:
data.groupby(['globalCallID_callManagerId', 'globalCallID_callId', 'dateOrigin']).count()

                                                           origLegCallIdentifier  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                      2
                           2                   2024-01-16                      2
                           3                   2024-01-16                      1
                           4                   2024-01-16                      2
                           5                   2024-01-16                      2
...                                                                          ...
4                          6319773             2024-03-29                      2
                           6319775             2024-03-30                      1
                           6319776             2024-03-30                      1
                           6319777             2024-03-30                      1
                           6319778             2024-03-31                      1

                                                           dateTimeOrigination  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                    2
                           2                   2024-01-16                    2
                           3                   2024-01-16                    1
                           4                   2024-01-16                    2
                           5                   2024-01-16                    2
...                                                                        ...
4                          6319773             2024-03-29                    2
                           6319775             2024-03-30                    1
                           6319776             2024-03-30                    1
                           6319777             2024-03-30                    1
                           6319778             2024-03-31                    1

                                                           callingPartyNumber  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                   2
                           2                   2024-01-16                   2
                           3                   2024-01-16                   1
                           4                   2024-01-16                   1
                           5                   2024-01-16                   2
...                                                                       ...
4                          6319773             2024-03-29                   2
                           6319775             2024-03-30                   1
                           6319776             2024-03-30                   1
                           6319777             2024-03-30                   1
                           6319778             2024-03-31                   1

                                                           origCause_value  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                2
                           2                   2024-01-16                2
                           3                   2024-01-16                1
                           4                   2024-01-16                2
                           5                   2024-01-16                2
...                                                                    ...
4                          6319773             2024-03-29                2
                           6319775             2024-03-30                1
                           6319776             2024-03-30                1
                           6319777             2024-03-30                1
                           6319778             2024-03-31                1

                                                           destLegIdentifier  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                  2
                           2                   2024-01-16                  2
                           3                   2024-01-16                  1
                           4                   2024-01-16                  2
                           5                   2024-01-16                  2
...                                                                      ...
4                          6319773             2024-03-29                  2
                           6319775             2024-03-30                  1
                           6319776             2024-03-30                  1
                           6319777             2024-03-30                  1
                           6319778             2024-03-31                  1

                                                           originalCalledPartyNumber  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                          2
                           2                   2024-01-16                          2
                           3                   2024-01-16                          1
                           4                   2024-01-16                          2
                           5                   2024-01-16                          2
...                                                                              ...
4                          6319773             2024-03-29                          2
                           6319775             2024-03-30                          1
                           6319776             2024-03-30                          1
                           6319777             2024-03-30                          1
                           6319778             2024-03-31                          1

                                                           finalCalledPartyNumber  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                       2
                           2                   2024-01-16                       2
                           3                   2024-01-16                       1
                           4                   2024-01-16                       2
                           5                   2024-01-16                       2
...                                                                           ...
4                          6319773             2024-03-29                       2
                           6319775             2024-03-30                       1
                           6319776             2024-03-30                       1
                           6319777             2024-03-30                       1
                           6319778             2024-03-31                       1

                                                           destCause_value  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                2
                           2                   2024-01-16                2
                           3                   2024-01-16                1
                           4                   2024-01-16                2
                           5                   2024-01-16                2
...                                                                    ...
4                          6319773             2024-03-29                2
                           6319775             2024-03-30                1
                           6319776             2024-03-30                1
                           6319777             2024-03-30                1
                           6319778             2024-03-31                1

                                                           dateTimeConnect  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                2
                           2                   2024-01-16                2
                           3                   2024-01-16                1
                           4                   2024-01-16                2
                           5                   2024-01-16                2
...                                                                    ...
4                          6319773             2024-03-29                2
                           6319775             2024-03-30                1
                           6319776             2024-03-30                1
                           6319777             2024-03-30                1
                           6319778             2024-03-31                0

                                                           dateTimeDisconnect  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                   2
                           2                   2024-01-16                   2
                           3                   2024-01-16                   1
                           4                   2024-01-16                   2
                           5                   2024-01-16                   2
...                                                                       ...
4                          6319773             2024-03-29                   2
                           6319775             2024-03-30                   1
                           6319776             2024-03-30                   1
                           6319777             2024-03-30                   1
                           6319778             2024-03-31                   1

                                                           ...  \
globalCallID_callManagerId globalCallID_callId dateOrigin  ...
1                          1                   2024-01-16  ...
                           2                   2024-01-16  ...
                           3                   2024-01-16  ...
                           4                   2024-01-16  ...
                           5                   2024-01-16  ...
...                                                        ...
4                          6319773             2024-03-29  ...
                           6319775             2024-03-30  ...
                           6319776             2024-03-30  ...
                           6319777             2024-03-30  ...
                           6319778             2024-03-31  ...

                                                           origDeviceName  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16               2
                           2                   2024-01-16               2
                           3                   2024-01-16               1
                           4                   2024-01-16               1
                           5                   2024-01-16               2
...                                                                   ...
4                          6319773             2024-03-29               2
                           6319775             2024-03-30               1
                           6319776             2024-03-30               1
                           6319777             2024-03-30               1
                           6319778             2024-03-31               1

                                                           destDeviceName  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16               2
                           2                   2024-01-16               2
                           3                   2024-01-16               1
                           4                   2024-01-16               2
                           5                   2024-01-16               2
...                                                                   ...
4                          6319773             2024-03-29               2
                           6319775             2024-03-30               1
                           6319776             2024-03-30               1
                           6319777             2024-03-30               1
                           6319778             2024-03-31               1

                                                           origCallTerminationOnBehalfOf  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                              2
                           2                   2024-01-16                              2
                           3                   2024-01-16                              1
                           4                   2024-01-16                              2
                           5                   2024-01-16                              2
...                                                                                  ...
4                          6319773             2024-03-29                              2
                           6319775             2024-03-30                              1
                           6319776             2024-03-30                              1
                           6319777             2024-03-30                              1
                           6319778             2024-03-31                              1

                                                           destCallTerminationOnBehalfOf  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                              2
                           2                   2024-01-16                              2
                           3                   2024-01-16                              1
                           4                   2024-01-16                              2
                           5                   2024-01-16                              2
...                                                                                  ...
4                          6319773             2024-03-29                              2
                           6319775             2024-03-30                              1
                           6319776             2024-03-30                              1
                           6319777             2024-03-30                              1
                           6319778             2024-03-31                              1

                                                           origCalledPartyRedirectOnBehalfOf  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                                  2
                           2                   2024-01-16                                  2
                           3                   2024-01-16                                  1
                           4                   2024-01-16                                  2
                           5                   2024-01-16                                  2
...                                                                                      ...
4                          6319773             2024-03-29                                  2
                           6319775             2024-03-30                                  1
                           6319776             2024-03-30                                  1
                           6319777             2024-03-30                                  1
                           6319778             2024-03-31                                  1

                                                           lastRedirectRedirectOnBehalfOf  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                               2
                           2                   2024-01-16                               2
                           3                   2024-01-16                               1
                           4                   2024-01-16                               2
                           5                   2024-01-16                               2
...                                                                                   ...
4                          6319773             2024-03-29                               2
                           6319775             2024-03-30                               1
                           6319776             2024-03-30                               1
                           6319777             2024-03-30                               1
                           6319778             2024-03-31                               1

                                                           origCalledPartyRedirectReason  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                              2
                           2                   2024-01-16                              2
                           3                   2024-01-16                              1
                           4                   2024-01-16                              2
                           5                   2024-01-16                              2
...                                                                                  ...
4                          6319773             2024-03-29                              2
                           6319775             2024-03-30                              1
                           6319776             2024-03-30                              1
                           6319777             2024-03-30                              1
                           6319778             2024-03-31                              1

                                                           lastRedirectRedirectReason  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16                           2
                           2                   2024-01-16                           2
                           3                   2024-01-16                           1
                           4                   2024-01-16                           2
                           5                   2024-01-16                           2
...                                                                               ...
4                          6319773             2024-03-29                           2
                           6319775             2024-03-30                           1
                           6319776             2024-03-30                           1
                           6319777             2024-03-30                           1
                           6319778             2024-03-31                           1

                                                           joinOnBehalfOf  \
globalCallID_callManagerId globalCallID_callId dateOrigin
1                          1                   2024-01-16               2
                           2                   2024-01-16               2
                           3                   2024-01-16               1
                           4                   2024-01-16               2

In [11]:
data['unique_call_id'] = data.groupby(['globalCallID_callManagerId', 'globalCallID_callId', 'dateOrigin']).ngroup()

In [12]:
data['unique_call_id'].max()

np.int64(2781786)

In [13]:
data = data.drop(columns=['dateOrigin'])

In [14]:
data

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus,unique_call_id
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,HK010_CC,12,0,0,0,0,0,0,0,752520
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,HK010_CC,12,0,0,0,0,0,0,0,752521
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,HK010_CC,12,0,0,0,0,0,0,0,752522
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,HK010_CC,12,0,0,0,0,0,0,0,752523
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,HK010_CC,0,12,0,0,0,0,0,0,752524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3805581,4,6319773,68494904,2024-03-29 19:15:54,43204838804831,0,68494909,43204838804829,5058900,16,...,Unity_Connection_Publisher,1,12,5,1,178,18,1,0,2781782
3805582,4,6319775,68495018,2024-03-30 15:12:29,434005336339264,16,68495019,50335447441930,50335447441930,0,...,BK053_079_Tele2,12,0,0,0,0,0,0,0,2781783
3805583,4,6319776,68495025,2024-03-30 15:34:07,434005336339264,16,68495026,50335447441930,50335447441930,0,...,BK053_079_Tele2,12,0,0,0,0,0,0,0,2781784
3805584,4,6319777,68495037,2024-03-30 18:13:14,432537661412,0,68495038,2868767180,2868767180,16,...,BK044_000_Tele2,0,12,0,0,0,0,0,0,2781785
3805585,4,6319778,68495119,2024-03-31 10:04:59,434424270388476,16,68495120,92854133396,92854133396,0,...,BK044_058_Tele2,12,0,0,0,0,0,0,0,2781786

In [15]:
data.to_pickle('cdr_clean_unique_calls.pkl')