In [10]:
import pandas as pd
import pickle
data = pd.read_pickle("cdr_clean.pkl")

In [11]:
data = data.drop(columns=['pkid'])

In [12]:
data.shape[0]

3805586

In [13]:
type(data.columns)

pandas.core.indexes.base.Index

In [14]:
counts = data.groupby(by=list(data.columns)).count()

In [15]:
counts.head()

Empty DataFrame
Columns: []
Index: [(1, 1, 20554141, 2024-01-16 10:11:47, 4369121193063, 393216, 20554142, +4321454093284, +4321454093284, 393216, 2024-01-16 10:11:52, 2024-01-16 10:11:52, +4321454093284, 0, HK010_CC, CSFC38K6092, 17, 17, 0, 0, 0, 0, 0, 0), (1, 1, 20554142, 2024-01-16 10:11:52, +4321454093284, 16, 20554096, +4369121193063, +4369121193063, 0, 2024-01-16 10:11:52, 2024-01-16 10:16:23, +4321454093284, 271, CSFC38K6092, BK053_000_Tele2, 12, 17, 0, 18, 0, 146, 18, 0), (1, 2, 20554145, 2024-01-16 10:11:49, 4368926414697, 393216, 20554148, +4368883460773, +436356240905, 393216, 2024-01-16 10:11:49, 2024-01-16 10:11:49, +4368883460773, 0, HK010_CC, Unity_Connection_Publisher, 17, 17, 5, 5, 15, 15, 5, 0), (1, 2, 20554148, 2024-01-16 10:11:49, +436356240905, 0, 39184270, +4368926414697, +4368926414697, 16, 2024-01-16 10:11:49, 2024-01-16 10:12:25, +4368883460773, 36, Unity_Connection_Publisher, BK044_000_Tele2, 17, 12, 0, 18, 0, 146, 18, 0), (1, 3, 20554152, 2024-01-16 10:11:49, +498883250014, 393216, 20554155, +433277014100, +4344124999, 393216, 2024-01-16 10:11:50, 2024-01-16 10:12:29, +433277014100, 39, BK016_000_Tele2, HK010_CC, 18, 18, 5, 5, 15, 15, 5, 0)]

In [16]:
data[data.duplicated()==True]

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
3536363,1,363534,67747431,2024-02-20 13:05:01,0046133053414,0,67747687,+437134539429,+437134539429,27,...,BK044_000_Tele2,CSFC29KMCL,10,12,0,10,0,4,10,0

In [17]:
data[(data['globalCallID_callId']==363534) & (data['origLegCallIdentifier'] == 67747431)]

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
3536307,1,363534,67747431,2024-02-20 13:02:49,0046133053414,27,67747588,+435033022534,+435033022534,0,...,BK044_000_Tele2,<NA>,13,0,1,1,18,18,1,0
3536362,1,363534,67747431,2024-02-20 13:05:01,0046133053414,0,67747687,+437134539429,+437134539429,27,...,BK044_000_Tele2,CSFC29KMCL,10,12,0,10,0,4,10,0
3536363,1,363534,67747431,2024-02-20 13:05:01,0046133053414,0,67747687,+437134539429,+437134539429,27,...,BK044_000_Tele2,CSFC29KMCL,10,12,0,10,0,4,10,0
3536364,1,363534,67747431,2024-02-20 13:05:01,0046133053414,0,67747703,+437134539429,+437431370,0,...,BK044_000_Tele2,BK044_Main,1,1,5,5,178,178,5,0
3536398,1,363534,67747431,2024-02-20 13:05:01,0046133053414,393216,67747706,+437134539429,+435460889209,393216,...,BK044_000_Tele2,CSFC29KGTS,10,10,5,1,178,18,1,0
3536464,1,363534,67747431,2024-02-20 13:07:00,0046133053414,0,67747824,003738509500050,003738509500050,16,...,BK044_000_Tele2,BK044_000_Tele2,10,12,0,10,0,4,10,0

In [18]:
data_complete = pd.read_pickle(r"C:\Users\Lenka\Documents\data analýza\DA\PROJEKT\Hovory\zakl pandas\Staredata\all_cdr_files_in_one.pkl")

In [22]:
data_complete = data_complete.drop(columns=['pkid'])

C:\Users\Lenka\AppData\Local\Temp\ipykernel_19488\4061093556.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  data_complete = data_complete.drop(columns=['pkid'])

In [23]:
data_complete[data_complete.duplicated()]

,cdrRecordType,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,origNodeId,origSpan,origIpAddr,callingPartyNumber,callingPartyUnicodeLoginUserID,...,destMobileCallDuration,mobileCallType,originalCalledPartyPattern,finalCalledPartyPattern,lastRedirectingPartyPattern,huntPilotPattern,origDeviceType,destDeviceType,origDeviceSessionID,destDeviceSessionID
,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,VARCHAR(50),VARCHAR(128),...,INTEGER,INTEGER,VARCHAR(50),VARCHAR(50),VARCHAR(50),VARCHAR(50),VARCHAR(100),VARCHAR(100),VARCHAR(128),VARCHAR(128)
71,1,1,363534,67747431,1708434301,4,67747431,1387659530,0046133053414,NaN,...,0,0,+437134539429,+437134539429,+437134539212,NaN,NaN,NaN,10b1bdd94cbe50288dae6806b859f87b,0000479500105000a000bc0ff3712968

In [21]:
data_complete.shape

(3805586, 133)